/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Location {
  'lat' : number,
  'lng' : number,
  'osmNodeId' : string,
  'name' : string,
  'ratings' : Array<Rating>,
  'address' : [] | [string],
  'locationType' : LocationType,
}
export interface LocationInput {
  'lat' : number,
  'lng' : number,
  'osmNodeId' : string,
  'name' : string,
  'address' : [] | [string],
  'locationType' : LocationType,
}
export type LocationType = { 'CoworkingSpace' : null } |
  { 'Library' : null } |
  { 'Cafe' : null };
export type NoiseLevel = { 'Buzzing' : null } |
  { 'Moderate' : null } |
  { 'Quiet' : null };
export interface Profile { 'name' : string }
export interface Rating {
  'wifiSpeed' : WifiSpeed,
  'userId' : Principal,
  'createdAt' : Time,
  'description' : [] | [string],
  'updatedAt' : Time,
  'noiseLevel' : NoiseLevel,
  'editCount' : bigint,
}
export type Time = bigint;
export type WifiSpeed = { 'Fast' : null } |
  { 'Okay' : null } |
  { 'Slow' : null };
export interface _SERVICE {
  'checkIn' : ActorMethod<
    [LocationInput, NoiseLevel, WifiSpeed, [] | [string]],
    undefined
  >,
  'deleteMyRating' : ActorMethod<[string], undefined>,
  'getAllLocations' : ActorMethod<[], Array<Location>>,
  'getLocation' : ActorMethod<[string], [] | [Location]>,
  'getLocationsByNoise' : ActorMethod<[NoiseLevel], Array<Location>>,
  'getLocationsByType' : ActorMethod<[LocationType], Array<Location>>,
  'getMyRating' : ActorMethod<[string], [] | [Rating]>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'setProfile' : ActorMethod<[string], undefined>,
  'updateRating' : ActorMethod<
    [string, NoiseLevel, WifiSpeed, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];