/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LocationType = IDL.Variant({
  'CoworkingSpace' : IDL.Null,
  'Library' : IDL.Null,
  'Cafe' : IDL.Null,
});
export const LocationInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'osmNodeId' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'locationType' : LocationType,
});
export const NoiseLevel = IDL.Variant({
  'Buzzing' : IDL.Null,
  'Moderate' : IDL.Null,
  'Quiet' : IDL.Null,
});
export const WifiSpeed = IDL.Variant({
  'Fast' : IDL.Null,
  'Okay' : IDL.Null,
  'Slow' : IDL.Null,
});
export const Time = IDL.Int;
export const Rating = IDL.Record({
  'wifiSpeed' : WifiSpeed,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'noiseLevel' : NoiseLevel,
  'editCount' : IDL.Nat,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'osmNodeId' : IDL.Text,
  'name' : IDL.Text,
  'ratings' : IDL.Vec(Rating),
  'address' : IDL.Opt(IDL.Text),
  'locationType' : LocationType,
});
export const Profile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'checkIn' : IDL.Func(
      [LocationInput, NoiseLevel, WifiSpeed, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteMyRating' : IDL.Func([IDL.Text], [], []),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getLocationsByNoise' : IDL.Func(
      [NoiseLevel],
      [IDL.Vec(Location)],
      ['query'],
    ),
  'getLocationsByType' : IDL.Func(
      [LocationType],
      [IDL.Vec(Location)],
      ['query'],
    ),
  'getMyRating' : IDL.Func([IDL.Text], [IDL.Opt(Rating)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'updateRating' : IDL.Func(
      [IDL.Text, NoiseLevel, WifiSpeed, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LocationType = IDL.Variant({
    'CoworkingSpace' : IDL.Null,
    'Library' : IDL.Null,
    'Cafe' : IDL.Null,
  });
  const LocationInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'osmNodeId' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'locationType' : LocationType,
  });
  const NoiseLevel = IDL.Variant({
    'Buzzing' : IDL.Null,
    'Moderate' : IDL.Null,
    'Quiet' : IDL.Null,
  });
  const WifiSpeed = IDL.Variant({
    'Fast' : IDL.Null,
    'Okay' : IDL.Null,
    'Slow' : IDL.Null,
  });
  const Time = IDL.Int;
  const Rating = IDL.Record({
    'wifiSpeed' : WifiSpeed,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'noiseLevel' : NoiseLevel,
    'editCount' : IDL.Nat,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'osmNodeId' : IDL.Text,
    'name' : IDL.Text,
    'ratings' : IDL.Vec(Rating),
    'address' : IDL.Opt(IDL.Text),
    'locationType' : LocationType,
  });
  const Profile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'checkIn' : IDL.Func(
        [LocationInput, NoiseLevel, WifiSpeed, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteMyRating' : IDL.Func([IDL.Text], [], []),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getLocationsByNoise' : IDL.Func(
        [NoiseLevel],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'getLocationsByType' : IDL.Func(
        [LocationType],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'getMyRating' : IDL.Func([IDL.Text], [IDL.Opt(Rating)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'updateRating' : IDL.Func(
        [IDL.Text, NoiseLevel, WifiSpeed, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };