/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    ratings: Array<Rating>;
    address?: string;
    locationType: LocationType;
}
export type Time = bigint;
export interface Rating {
    wifiSpeed: WifiSpeed;
    userId: Principal;
    createdAt: Time;
    description?: string;
    updatedAt: Time;
    noiseLevel: NoiseLevel;
    editCount: bigint;
}
export interface LocationInput {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    address?: string;
    locationType: LocationType;
}
export interface Profile {
    name: string;
}
export enum LocationType {
    CoworkingSpace = "CoworkingSpace",
    Library = "Library",
    Cafe = "Cafe"
}
export enum NoiseLevel {
    Buzzing = "Buzzing",
    Moderate = "Moderate",
    Quiet = "Quiet"
}
export enum WifiSpeed {
    Fast = "Fast",
    Okay = "Okay",
    Slow = "Slow"
}
export interface backendInterface {
    checkIn(locationInput: LocationInput, noiseLevel: NoiseLevel, wifiSpeed: WifiSpeed, description: string | null): Promise<void>;
    deleteMyRating(osmNodeId: string): Promise<void>;
    getAllLocations(): Promise<Array<Location>>;
    getLocation(osmNodeId: string): Promise<Location | null>;
    getLocationsByNoise(noiseLevel: NoiseLevel): Promise<Array<Location>>;
    getLocationsByType(locationType: LocationType): Promise<Array<Location>>;
    getMyRating(osmNodeId: string): Promise<Rating | null>;
    getProfile(): Promise<Profile | null>;
    setProfile(name: string): Promise<void>;
    updateRating(osmNodeId: string, noiseLevel: NoiseLevel, wifiSpeed: WifiSpeed, description: string | null): Promise<void>;
}
import type { Location as _Location, LocationInput as _LocationInput, LocationType as _LocationType, NoiseLevel as _NoiseLevel, Profile as _Profile, Rating as _Rating, Time as _Time, WifiSpeed as _WifiSpeed } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkIn(arg0: LocationInput, arg1: NoiseLevel, arg2: WifiSpeed, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(to_candid_LocationInput_n1(this._uploadFile, this._downloadFile, arg0), to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg1), to_candid_WifiSpeed_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(to_candid_LocationInput_n1(this._uploadFile, this._downloadFile, arg0), to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg1), to_candid_WifiSpeed_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteMyRating(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyRating(arg0);
            return result;
        }
    }
    async getAllLocations(): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocations();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocations();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(arg0: string): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationsByNoise(arg0: NoiseLevel): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationsByNoise(to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationsByNoise(to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationsByType(arg0: LocationType): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationsByType(to_candid_LocationType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationsByType(to_candid_LocationType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRating(arg0: string): Promise<Rating | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRating(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRating(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async updateRating(arg0: string, arg1: NoiseLevel, arg2: WifiSpeed, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRating(arg0, to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg1), to_candid_WifiSpeed_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRating(arg0, to_candid_NoiseLevel_n5(this._uploadFile, this._downloadFile, arg1), to_candid_WifiSpeed_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_LocationType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationType): LocationType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_NoiseLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoiseLevel): NoiseLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_WifiSpeed_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WifiSpeed): WifiSpeed {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : from_candid_Location_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rating]): Rating | null {
    return value.length === 0 ? null : from_candid_Rating_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    ratings: Array<_Rating>;
    address: [] | [string];
    locationType: _LocationType;
}): {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    ratings: Array<Rating>;
    address?: string;
    locationType: LocationType;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        osmNodeId: value.osmNodeId,
        name: value.name,
        ratings: from_candid_vec_n13(_uploadFile, _downloadFile, value.ratings),
        address: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.address)),
        locationType: from_candid_LocationType_n21(_uploadFile, _downloadFile, value.locationType)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wifiSpeed: _WifiSpeed;
    userId: Principal;
    createdAt: _Time;
    description: [] | [string];
    updatedAt: _Time;
    noiseLevel: _NoiseLevel;
    editCount: bigint;
}): {
    wifiSpeed: WifiSpeed;
    userId: Principal;
    createdAt: Time;
    description?: string;
    updatedAt: Time;
    noiseLevel: NoiseLevel;
    editCount: bigint;
} {
    return {
        wifiSpeed: from_candid_WifiSpeed_n16(_uploadFile, _downloadFile, value.wifiSpeed),
        userId: value.userId,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.description)),
        updatedAt: value.updatedAt,
        noiseLevel: from_candid_NoiseLevel_n19(_uploadFile, _downloadFile, value.noiseLevel),
        editCount: value.editCount
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fast: null;
} | {
    Okay: null;
} | {
    Slow: null;
}): WifiSpeed {
    return "Fast" in value ? WifiSpeed.Fast : "Okay" in value ? WifiSpeed.Okay : "Slow" in value ? WifiSpeed.Slow : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Buzzing: null;
} | {
    Moderate: null;
} | {
    Quiet: null;
}): NoiseLevel {
    return "Buzzing" in value ? NoiseLevel.Buzzing : "Moderate" in value ? NoiseLevel.Moderate : "Quiet" in value ? NoiseLevel.Quiet : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CoworkingSpace: null;
} | {
    Library: null;
} | {
    Cafe: null;
}): LocationType {
    return "CoworkingSpace" in value ? LocationType.CoworkingSpace : "Library" in value ? LocationType.Library : "Cafe" in value ? LocationType.Cafe : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Location>): Array<Location> {
    return value.map((x)=>from_candid_Location_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rating>): Array<Rating> {
    return value.map((x)=>from_candid_Rating_n14(_uploadFile, _downloadFile, x));
}
function to_candid_LocationInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationInput): _LocationInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LocationType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): _LocationType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NoiseLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoiseLevel): _NoiseLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WifiSpeed_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WifiSpeed): _WifiSpeed {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    address?: string;
    locationType: LocationType;
}): {
    lat: number;
    lng: number;
    osmNodeId: string;
    name: string;
    address: [] | [string];
    locationType: _LocationType;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        osmNodeId: value.osmNodeId,
        name: value.name,
        address: value.address ? candid_some(value.address) : candid_none(),
        locationType: to_candid_LocationType_n3(_uploadFile, _downloadFile, value.locationType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): {
    CoworkingSpace: null;
} | {
    Library: null;
} | {
    Cafe: null;
} {
    return value == LocationType.CoworkingSpace ? {
        CoworkingSpace: null
    } : value == LocationType.Library ? {
        Library: null
    } : value == LocationType.Cafe ? {
        Cafe: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoiseLevel): {
    Buzzing: null;
} | {
    Moderate: null;
} | {
    Quiet: null;
} {
    return value == NoiseLevel.Buzzing ? {
        Buzzing: null
    } : value == NoiseLevel.Moderate ? {
        Moderate: null
    } : value == NoiseLevel.Quiet ? {
        Quiet: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WifiSpeed): {
    Fast: null;
} | {
    Okay: null;
} | {
    Slow: null;
} {
    return value == WifiSpeed.Fast ? {
        Fast: null
    } : value == WifiSpeed.Okay ? {
        Okay: null
    } : value == WifiSpeed.Slow ? {
        Slow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
